# Generated by Django 4.1.5 on 2023-03-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.TextField()),
                ('price', models.TextField()),
                ('photo1', models.TextField()),
                ('photo2', models.TextField()),
                ('type', models.TextField()),
                ('type_connection', models.TextField()),
                ('enterface', models.TextField()),
                ('color', models.TextField()),
                ('anti_shum', models.TextField()),
                ('ambushur', models.TextField()),
                ('type_vipe', models.TextField()),
                ('date_create', models.TextField()),
                ('country', models.TextField()),
                ('garantee', models.TextField()),
                ('time_work', models.TextField()),
                ('description', models.TextField(default='1')),
                ('weight', models.TextField(default='1')),
                ('corpus', models.TextField(default='1')),
                ('vid', models.TextField(default='1')),
                ('dop_infa', models.TextField(default='1')),
                ('types', models.TextField(default='extra')),
                ('count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('photo1', models.TextField()),
                ('photo2', models.TextField()),
                ('photo3', models.TextField()),
                ('description', models.TextField()),
                ('version_os', models.TextField()),
                ('corpus', models.TextField()),
                ('sim_card', models.TextField()),
                ('size', models.TextField()),
                ('weight', models.TextField()),
                ('display_type', models.TextField()),
                ('diagonale', models.TextField()),
                ('allow_display', models.TextField()),
                ('photo_kamera', models.TextField()),
                ('front_kamera', models.TextField()),
                ('headphone_jack', models.TextField()),
                ('standart', models.TextField()),
                ('interface', models.TextField()),
                ('prochessor', models.TextField()),
                ('yadra', models.TextField()),
                ('giga_vstoeno', models.TextField()),
                ('giga_operate', models.TextField()),
                ('sloy_card', models.TextField()),
                ('accumulator', models.TextField()),
                ('dop_infa', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.TextField()),
                ('audio', models.TextField(default='hello')),
                ('types', models.TextField(default='смартфон')),
                ('count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('username', models.TextField(default='1')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phones')),
            ],
        ),
        migrations.CreateModel(
            name='Bascet_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_product', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_buy', models.BooleanField(default=False)),
                ('name', models.TextField(default='1')),
                ('price', models.IntegerField(default=0)),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirPods_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('username', models.TextField(default='1')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('airpod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.airpods')),
            ],
        ),
    ]
