# Generated by Django 4.1.5 on 2023-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpods_comments',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone_comments',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
