# Generated by Django 4.1.5 on 2023-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_bascet_products_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bascet_products',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bascet_products',
            name='image',
            field=models.TextField(default='bref'),
        ),
        migrations.AddField(
            model_name='bascet_products',
            name='slug',
            field=models.SlugField(default='zero', max_length=255, unique=True),
        ),
    ]
