# Generated by Django 4.1.5 on 2023-03-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_bascet_products_count_bascet_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascet_products',
            name='slug',
            field=models.TextField(default='ok'),
        ),
    ]
